language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t junior-elf/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true junior-elf/docker-react npm run test

